### ISSUE TITLE
pwa-amp-sw.js 404

### ISSUE THREAD

**Issue by thr4sher** [ahmedkaludi/pwa-for-wp#111]
Hello,
I have installed the module from the "amp for wp" plugin but when i have uninstalled it this message appears on the browser console: "A bad HTTP response code (404) was received when fetching the script." -> pwa-amp-sw.js

how can I uninstall definitively the module pwa-for-wp? why wp still trying to load this js? :|

**Comment by ahmedkaludi** [comment]
please contact us directly on http://pwa-for-wp.com/contact/ for support

**Comment by eksiscloud** [comment]
You should answer public because this is still an issue even 2021.

**Comment by ahmedkaludi** [comment]
@eksiscloud please contact us directly on http://pwa-for-wp.com/contact/ for support

**Comment by helisoncruz** [comment]
> You should answer public because this is still an issue even 2021.

Since it was from 2021 this should be answered publicly, as I have encountered several variations of this problem and no real answer.

I also uninstalled the plugin, because it was causing extreme slowness to my site, and even after removed, see what a surprise, the file `pwa-amp-sw.js` processing hundreds of requests and making things even slower.

Any solution?

**Comment by examsegg** [comment]
I confirm this issue exists in 2023 as well (pwa-amp-sw.js processing hundreds of requests even after un-installing the both plugins).
As the solution, I have deleted this file from the website root (not sure if it is the right solution). Hope it is.
