### ISSUE TITLE
Call to action is not working

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/pwa-for-wp#232]
- [x] call to action is not working. the user keeps getting the black screen.

- [x] two call to action is coming. and both overlapping each other.

- [ ] user chooses login as a start page but still, it returns an empty page, not a login page.

Ref: https://secure.helpscout.net/conversation/988062529/94002/

**Comment by amer07** [comment]
Case- II

https://secure.helpscout.net/conversation/992388636/95258?folderId=2770543

Note:  Call to action custom bar appears behind the typical PWA bar, the correct would be that the plugin only shows the call to action bar instead of the typical "add to home screen" PWA bar, I mean, only one of the two bars, yours, the custom.

**Comment by ajeetku** [comment]
Some Settings issue Resolve in the update of 1.7.2
