### ISSUE TITLE
PWA not caching encoded content gzip

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/pwa-for-wp#613]
If contents are responding with gzip encoded, HTML files are not caching in this case

 https://staging-tlrkickstartpwa.kinsta.cloud/dashboard/
 
 https://secure.helpscout.net/conversation/1464526350/187780?folderId=4074390

**Comment by ajeetku** [comment]
https://secure.helpscout.net/conversation/1464526350/187780?folderId=4074390

**Comment by ajeetku** [comment]
Currently encoded contents getting 0 length

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/208882783-7bf0f037-c652-4a87-b713-1f09220b9878.png)

It seems to be setting issue , since **https://kickstart.thelastreformation.com/** is added to never cache which effectively means  never cache urls containing **https://kickstart.thelastreformation.com/** that is why even a single page is not cached except offline page.
Since logins are not working , user settings couldn't be updated

**Comment by akshaywali** [comment]
closing this ticket  since this is a user side setting issue
