### ISSUE TITLE
Add notification badge on the PWA icon

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/pwa-for-wp#644]
Add notification badge(number of notifications) on the PWA icon

Ref: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by michael-newman** [comment]
@ajeetku, adding the notification badge on the PWA icon would add a lot of value to your recent Ultimate Member (UM) real-time notification integration--Since the UM notifications are personalized for each user, this would be highly valued by the PWA User. Really hope you can prioritize this request. Thank you, Mike

**Comment by ajeetku** [comment]
Released with [Pushnotification](https://wordpress.org/plugins/push-notification) version 1.21
