### ISSUE TITLE
Getting blank page when trying to access the BuddyBoss plugin using " Buddypress for PWAforWP " extension

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/pwa-for-wp#704]
Getting " You are not allowed to access this page " message when trying to access the BuddyBoss plugin using " Buddypress for PWAforWP " extension.

ref - https://monosnap.com/direct/4iBEqMHXYyGmwyiMKfxbCZwmHveKKh

helpscout link - https://secure.helpscout.net/conversation/1861365726/239418?folderId=1060556

**Comment by 77naveenop** [comment]
Another user with the same issue. Also, the user said, "The problem is that if Buddyboss is installed you cannot install also Buddypress, so you can't have the Buddypress option panel. This is confirmed by the Buddyboss authors".

Reference URL -: https://secure.helpscout.net/conversation/1891393042/243624?folderId=5893230

**Comment by pradipshende** [comment]
Pushed in BuddyPress for PWA for WP plugin version 1.3.2

**Comment by pradipshende** [comment]
Pushed in Offline Forms for PWA for WP plugin version 1.4
