### ISSUE TITLE
We have to refund this customer due to the issues in PWAforWP-Test the issue

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#710]
**We need to test the issue mentioned below.**
Issue reported by the customer:

1. Our site crashed literally and we emailed you for help using the premium support. The pull to refresh crashed our site every tine some1 pulled to refresh. We thought we would not use it if others worked.

2. Your plugin is not compatible with rtMedia or videos.They froze all our media and we could not even for a day upload any videos. Your pluggin caused us considerable inconvenience on two of our sites but we don't blame the product since sometimes plugins don't work with other plugins. We are sure you are constantly working to improve your product.

Helpscout link: https://secure.helpscout.net/conversation/1880633985/242081?folderId=6368936

**Comment by akshaywali** [comment]
Tested for the above issue for :
PHP (8.0)
- WordPress (6.1.1) 
- BuddyPress (10.6.0) 
- PWA for WP(1.7.54)
- Pull to Refresh for PWA  (1.6)
- rtMedia for WordPress, BuddyPress and bbPress (4.6.13)

1.There was no issue on website and  no error or notice was logged to debug.log either. Query Monitor also did not showed anything unusual.
2. rtMedia uploads was working fine on android but on iOS video and audio file were not uploaded since rtmedia by default supports only mp4 for video and mp3 for audio. (iOS has MOV for video and m4a/aac for audio)
After allowing custom file types(MOV,AAC,M4a ) upload were working on iOS too.
Ref for allowing custom files types on rtmedia https://rtmedia.io/docs/developers/allow-custom-media-types/

**So PWA for WP is working fine with rtmedia plugin just user  have to unable   files types to make sure iOS users are  allowed to upload media files**

**Other point to note is that on uploading larger file it will take some time for upload.**
