### ISSUE TITLE
One Signal issues with Progressive Web Apps

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/pwa-for-wp#81]
Ref:  https://secure.helpscout.net/conversation/778121208/55450?folderId=1914712

**Comment by Josimarcsilva** [comment]
Hi,
Your plugin is incompatible with OneSignal.

The user enables notifications and then two or three updates to the home screen or page change on the OneSignal site once again requests permission to send notifications.

I already did all the tests and problem only happens when your plugin is enabled. Your plugin settings are correct (your suport already checked).

I believe the problem is related to the generation of two manifest files. One generated by your plugin and another generated by Onesignal

Please see all screens attached.

The application address is: https://modelo.meugabinete.pro/
Enter the address above and enable OneSignal. Then refresh the browser two times or three times and see onesignal request re-enable notification.

My application and FTP credentials have been sent to your email.

![Erro001](https://user-images.githubusercontent.com/4340052/55275949-0576f980-52cc-11e9-91bf-987c3c05c394.jpeg)
![Erro002](https://user-images.githubusercontent.com/4340052/55275950-060f9000-52cc-11e9-9f49-e7131669ee45.jpeg)
![Erro003](https://user-images.githubusercontent.com/4340052/55275951-060f9000-52cc-11e9-97cb-c7a67f040085.jpeg)
![Erro004](https://user-images.githubusercontent.com/4340052/55275952-060f9000-52cc-11e9-84a3-1c8e17169f75.jpeg)
![Erro005](https://user-images.githubusercontent.com/4340052/55275953-060f9000-52cc-11e9-9b3e-cd9744f27db6.jpeg)
![Erro006](https://user-images.githubusercontent.com/4340052/55275954-06a82680-52cc-11e9-8800-ca7aac4465a7.jpeg)
![ErroManifest1](https://user-images.githubusercontent.com/4340052/55275955-06a82680-52cc-11e9-8aab-3239c57b939e.jpg)
![ErroManifest2](https://user-images.githubusercontent.com/4340052/55275956-06a82680-52cc-11e9-8ea5-340415df5b76.jpg)

**Comment by amer07** [comment]
Here one more user ref: https://secure.helpscout.net/conversation/882231013/71102/
