### ISSUE TITLE
Request/suggestion: Enable Web Share Target capability

### ISSUE THREAD

**Issue by SentLive** [ahmedkaludi/pwa-for-wp#887]
I'm sure I am not the only one who would like my users to have the option to share stuff directly to my site (specifically to their Buddypress Activity feed in my case) from either other social media, from their device etc. I have only just started looking into it but it seems it requires the Web Share Target API as outlined at https://developer.chrome.com/docs/capabilities/web-apis/web-share-target
Are there any plans  to implement this in the default manifest, or would I be able to implement it myself - is there anything that might prevent it? I am also guessing that iOS doesn't yet support this for PWAs but can you confirm?

**Comment by Sanjeevsetu** [comment]
Hi @SentLive 

Thanks for the suggesting new feature. We actually planned it many years ago but due to some internal issues, We could not move it further. Now, We are very soon going to implement this feature. It is related/duplicate ticket of https://github.com/ahmedkaludi/pwa-for-wp/issues/159 so We close your ticket and would continue development there.

**Comment by kumawatvikas** [comment]
Hi @SentLive  
By default buddypress activity feed does not allow to upload media files, it might need other plugins or theme to enable uploading feature, how you are doing this or what plugin/theme you are using?
